#!/usr/bin/env bash
# PostToolUse (Edit|Write) hook: the worker can't import workspace packages
# (lk agent deploy builds worker/ standalone), so canonical shared code is
# VENDORED into worker/src/vendor/ by `pnpm sync:worker`. This hook reminds you
# to re-run that copy when you edit a canonical shared file, and warns loudly if
# you hand-edit a generated vendor file. Advisory only — always exits 0.
#
# Reads the PostToolUse JSON on stdin (tool_input.file_path). Also honors the
# CLAUDE_FILE_PATHS env var if present (space/newline-separated).
set -euo pipefail

input="$(cat 2>/dev/null || true)"

# Collect candidate paths: the stdin file_path plus any CLAUDE_FILE_PATHS.
paths=""
if [ -n "$input" ] && command -v jq >/dev/null 2>&1; then
  paths="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)"
fi
if [ -z "$paths" ] && [ -n "$input" ]; then
  # Fallback without jq: crude extraction of the first file_path value.
  paths="$(printf '%s' "$input" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)"
fi
if [ -n "${CLAUDE_FILE_PATHS:-}" ]; then
  paths="$paths
${CLAUDE_FILE_PATHS}"
fi

[ -z "${paths//[[:space:]]/}" ] && exit 0

# Reminder: a canonical shared file changed — the worker's vendored copy must be
# regenerated with `pnpm sync:worker`.
remind_source() {
  printf '\n\033[1;33m⚠  CANONICAL SHARED FILE EDITED\033[0m — %s\n' "$1" >&2
  printf '   The worker builds standalone (lk agent deploy) and can NOT import this package.\n' >&2
  printf '   Re-vendor it into worker/src/vendor/ so the worker picks up your change:\n' >&2
  printf '       pnpm sync:worker\n' >&2
  printf '   (CI/verify runs `pnpm sync:worker --check` to fail on drift.)\n\n' >&2
}

# Warning: someone hand-edited a GENERATED vendor file — changes will be clobbered.
warn_vendor() {
  printf '\n\033[1;31m⛔  GENERATED VENDOR FILE EDITED\033[0m — %s\n' "$1" >&2
  printf '   worker/src/vendor/ is generated by `pnpm sync:worker` and carries a\n' >&2
  printf '   DO-NOT-EDIT header. Your edit will be overwritten. Edit the canonical file\n' >&2
  printf '   in packages/shared/src/ instead, then run `pnpm sync:worker`.\n\n' >&2
}

hit=0
kind=""
while IFS= read -r p; do
  [ -z "$p" ] && continue
  case "$p" in
    */worker/src/vendor/*|worker/src/vendor/*)
      warn_vendor "$p"; hit=1; kind="vendor" ;;
    */packages/shared/src/*.ts|packages/shared/src/*.ts)
      remind_source "$p"; hit=1; kind="source" ;;
  esac
done <<EOF
$paths
EOF

# Surface a durable note to the model too (only when we matched something).
if [ "$hit" -eq 1 ] && command -v jq >/dev/null 2>&1; then
  if [ "$kind" = "vendor" ]; then
    jq -n '{hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:"A generated file under worker/src/vendor/ was just edited. It is regenerated from packages/shared/src/ by `pnpm sync:worker` and will be overwritten. Edit the canonical file in packages/shared/src/ instead, then run `pnpm sync:worker`. See CLAUDE.md \"vendored worker code\"."}}'
  else
    jq -n '{hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:"A canonical shared file (packages/shared/src/) was just edited. The worker builds standalone and can not import it — run `pnpm sync:worker` to re-vendor it into worker/src/vendor/, then re-typecheck the worker. See CLAUDE.md \"vendored worker code\"."}}'
  fi
fi

exit 0
