import { llm, voice } from "@livekit/agents";
import { reportEvent } from "../gateway.js";
import { buildTools } from "../tools.js";
// Vendored copy of the canonical slug scheme (packages/shared/src/slugify.ts,
// also used by the gateway's agent-config schema). The worker builds standalone
// via `lk agent deploy`, so it can't import the workspace package —
// worker/src/vendor/ is regenerated by `pnpm sync:worker`. Exit-tool ids the LLM
// sees (`exit_${sanitize(name)}`) must equal the ids the gateway generated with
// the same transform, so both sides MUST derive from this one source.
import { slugify as sanitize } from "../vendor/slugify.js";
import { compactChatContext, type FlowRuntimeContext, tagRulesSatisfied } from "./context.js";
import type { ObjectivesTracker, ResolvedTarget } from "./objectives.js";

/**
 * Per-node agent assembly. A flow runs as a graph of small agents — one per
 * agent node, each with its own stage instructions and gated tools — connected
 * by exit tools that hand the session off to the next node (chat context
 * carried over, the previous node's prompt dropped).
 */

export interface AgentBuilder {
	buildFlowAgent(nodeId: string, chatCtx?: llm.ChatContext): voice.Agent;
}

export interface AgentBuilderDeps {
	resolveTarget(target: string | undefined): Promise<ResolvedTarget>;
	/** simulated/cold: ends the LLM turn (throws StopResponse). warm: resolves
	 * with a result string once the attended transfer merges the parties. */
	runTransfer(nodeId: string): Promise<string>;
	/** Exit-tool entry into an agent-handoff (flow `handoff` node): start the
	 * detached fetch+swap sequence, then end the LLM turn with no reply. */
	runHandoff(target: {
		agentId: string;
		fromNode: string;
		transition?: { say?: string; holdSeconds?: number };
	}): never;
	/** The objectives tracker is constructed after this builder (it depends on
	 * buildFlowAgent), so it is reached lazily from onEnter. */
	getObjectivesTracker(): ObjectivesTracker;
	/** Fired from the ENTRY node's onEnter (once its activity is live). Set only
	 * when this build is a handoff target — flow/handoff's speak-first nudge.
	 * The call's own first agent passes none (the greeting opens the call). */
	entryOnEnter?: () => void;
}

export function createAgentBuilder(ctx: FlowRuntimeContext, deps: AgentBuilderDeps): AgentBuilder {
	const { flow, nodesById, dispatch, bundle } = ctx;
	const { resolveTarget, runTransfer, runHandoff, getObjectivesTracker, entryOnEnter } = deps;

	/**
	 * Shared tail of every exit tool (regular exits and scenario exits):
	 * resolve the target through routers/statements, then hand off, hang up, or
	 * let an already-scheduled post-speech hangup run its course.
	 */
	const followTarget = async (
		target: string | undefined,
		runCtx: voice.RunContext,
	): Promise<string | llm.AgentHandoff> => {
		// Routers/statements between here and the next agent node are evaluated
		// inline (routers: one LLM pass; statements: a queued say).
		const resolved = await resolveTarget(target);
		if (resolved.kind === "end") {
			// Abort-tolerant: caller may disconnect mid-playout (see end_call).
			await runCtx.waitForPlayout().catch(() => {});
			await ctx.hangUp("flow_complete");
			return "call ended";
		}
		if (resolved.kind === "end_after_speech") {
			// A terminal statement was queued and will hang up after playout —
			// do NOT hang up (or await playout) here: awaiting a queued speech
			// from inside a tool execution risks the drain deadlock.
			return "call ending";
		}
		if (resolved.kind === "transfer") {
			return runTransfer(resolved.nodeId);
		}
		if (resolved.kind === "handoff") {
			return runHandoff({
				agentId: resolved.agentId,
				fromNode: resolved.fromNode,
				transition: resolved.transition,
			});
		}
		const nextCtx = runCtx.session.currentAgent.chatCtx.copy({
			excludeInstructions: true,
		});
		return llm.handoff({
			agent: buildFlowAgent(resolved.id, nextCtx),
			returns: `Moved to stage "${nodesById.get(resolved.id)?.name ?? resolved.id}".`,
		});
	};

	const buildFlowAgent = (nodeId: string, chatCtx?: llm.ChatContext): voice.Agent => {
		// Stamp every node→node swap: end_call refuses to fire near a transition,
		// so a model emitting end_call in the SAME turn as an exit tool (parallel
		// tool calls) can't kill the call mid-swap.
		ctx.state.lastTransitionAt = Date.now();
		const node = nodesById.get(nodeId);
		if (!node) throw new Error(`flow node "${nodeId}" not found`);
		if (
			node.kind === "router" ||
			node.kind === "statement" ||
			node.kind === "transfer" ||
			node.kind === "handoff"
		) {
			throw new Error(
				`flow node "${nodeId}" is a ${node.kind} — routers, statements, transfers and handoffs are evaluated inline via resolveTarget and never become agents`,
			);
		}

		// Rolling-memory compaction on node handoff (Phase 3): cap the carried-over
		// responder history to the last windowTurns verbatim turns; the condensed
		// older context rides in the `## CONVERSATION SO FAR` block below. Only the
		// responder-facing chatCtx is trimmed — `ctx.turns` (flush + judge) is untouched.
		if (chatCtx && ctx.memory.enabled) {
			const before = chatCtx.items.length;
			compactChatContext(chatCtx, ctx.memory.windowTurns);
			if (chatCtx.items.length < before) {
				reportEvent(dispatch.callId, "flow.memory_compact", {
					before,
					after: chatCtx.items.length,
					site: "handoff",
					node: node.id,
				});
			}
		}

		// Conversation mode (Phase 2): objective-less, self-driven open-ended
		// discovery. Mutually exclusive with objectives (schema-enforced).
		const conversation = node.conversation;
		const isConversation = !!conversation;
		const objectives = isConversation ? [] : (node.objectives ?? []);
		const hasObjectives = objectives.length > 0;

		// KNOWN CONTACT INFO (Phase 1 — the UNRESOLVED block). Rendered fresh on
		// every node entry from the shared mutable contactState, so a field written
		// in an earlier node shows its value here instead of UNRESOLVED. CRITICAL:
		// "UNRESOLVED" lives ONLY in this model-facing instruction string — it is
		// never a variable and never reaches interpolateSpoken/say, so it can never
		// be spoken. Empty list → no block at all.
		const contactInfo =
			ctx.contactState.length > 0
				? `\n\n## KNOWN CONTACT INFO\nYou already know these details about the caller. NEVER ask for a value shown here — if you need one, weave it in or confirm it naturally instead of asking. A field shown as UNRESOLVED is still unknown; those you MAY ask about. Never say the word "UNRESOLVED" aloud.\n${ctx.contactState
						.map((e) => `${e.label} -> ${e.value != null && e.value !== "" ? e.value : "UNRESOLVED"}`)
						.join("\n")}`
				: "";

		// Rolling summary (Phase 3): a condensed record of earlier turns, injected
		// into EVERY node kind between the global/stage instructions and the KNOWN
		// CONTACT INFO block. Empty until the first interval fires; a stale value is fine.
		const summaryText = ctx.rollingSummary.text.trim();
		const summaryBlock = summaryText
			? `\n\n## CONVERSATION SO FAR\nEarlier parts of this call, condensed (the most recent exchanges are still verbatim in the conversation below). Use this for continuity — never re-ask something already covered here:\n${summaryText}`
			: "";

		// Conversation-mode blocks (Phase 2). The reason (+ optional hints) replaces
		// the objectives block; closure is explicit rather than emergent.
		const conversationReasonBlock = isConversation
			? `\n\n## CONVERSATION REASON\n${ctx.interpolate(conversation!.reason)}${
					conversation!.hints?.length
						? `\n\nTalking points you can naturally explore (not a checklist — follow the caller's lead, one question at a time):\n${conversation!.hints
								.map((h) => `- ${ctx.interpolate(h)}`)
								.join("\n")}`
						: ""
				}`
			: "";
		const wrapUp = conversation?.wrapUp;
		const closeAction =
			wrapUp?.mode === "exit"
				? `call the exit_${sanitize(wrapUp.exit)} tool to move on`
				: "use the end_call tool to hang up";
		const wrapUpBlock = isConversation
			? `\n\n## WRAPPING UP\nYour DEFAULT is to KEEP THE CONVERSATION GOING: ask genuine, open-ended follow-up questions — ONE per reply — letting each answer lead naturally to the next angle. Do NOT wrap up just because a topic was covered; move to a fresh angle instead. Bring the call to a close ONLY when the CALLER clearly signals they are finished — they explicitly say they have nothing else or no more questions, they say goodbye, or they give repeated short, disengaged replies. When that clear signal comes, warmly acknowledge in ONE short line and then ${closeAction}. Never ask a question and end the call in the same reply: if you ask something, stop and wait for the answer.`
			: "";

		const nodeTools = buildTools(
			bundle.tools.filter((t) => node.toolIds.includes(t.id as string)),
			dispatch,
		);
		// Tag-driven exit gating (Phase 5b): an exit whose tagRules aren't
		// satisfied by the current tag set is NOT exposed here (and the objectives
		// primary falls through to the first non-gated exit). Evaluated at build
		// time — a mid-node tag change takes effect on the next handoff, when this
		// node (or the next) is rebuilt.
		const nonGatedExits = node.exits.filter((e) => tagRulesSatisfied(e.tagRules, ctx.contactTags));
		if (nonGatedExits.length < node.exits.length) {
			reportEvent(dispatch.callId, "flow.exits_gated", {
				node: node.id,
				gated: node.exits.filter((e) => !nonGatedExits.includes(e)).map((e) => e.name),
			});
		}
		// With objectives, the primary exit (the first NON-GATED exit) belongs to
		// the ENGINE — the judge takes it once the data is verified; the model gets
		// no tool for it (this is what stops eager exits). Secondary non-gated exits
		// ("Wrong number") stay model-callable. All exits gated → no primary: the
		// engine ends/continues per current no-exit semantics (warned below).
		const objectivesPrimary = hasObjectives ? nonGatedExits[0] : undefined;
		if (hasObjectives && node.exits.length > 0 && !objectivesPrimary) {
			reportEvent(dispatch.callId, "flow.no_available_exit", {
				node: node.id,
				reason: "all exits gated by tagRules",
			});
			console.warn(`flow: node "${node.id}" has objectives but every exit is tag-gated — objectives will end the call`);
		}
		const toolExits = hasObjectives ? nonGatedExits.slice(1) : nonGatedExits;
		// Guards against duplicate exit invocations from this node instance —
		// e.g. preemptiveGeneration drafting a reply (incl. tool calls) off an
		// interim transcript, then generating a second, final reply that calls
		// the same exit tool again once the caller's turn actually ends. Both
		// calls have real side effects (reportEvent + followTarget/handoff), so
		// the second one must be a no-op rather than replaying the transition.
		let exited = false;
		for (const exit of toolExits) {
			const target = exit.target;
			nodeTools[`exit_${sanitize(exit.name)}`] = llm.tool({
				description: `Take the "${exit.name}" exit: ${exit.description}${
					target ? "" : " This ends the call — say a brief goodbye first."
				}`,
				parameters: ctx.EMPTY_PARAMS,
				execute: async (_args, { ctx: runCtx }) => {
					if (exited) return "already handled";
					exited = true;
					reportEvent(dispatch.callId, "flow.exit", {
						node: node.id,
						exit: exit.name,
						target: target ?? null,
					});
					return followTarget(target, runCtx);
				},
			});
		}
		// Global scenarios (detect-and-jump): one extra exit per scenario on
		// every agent node, except a scenario already targeting this node.
		const scenarios = (flow.scenarios ?? []).filter((s) => s.target !== node.id);
		for (const scenario of scenarios) {
			nodeTools[`exit_scenario_${sanitize(scenario.name)}`] = llm.tool({
				description: `SCENARIO — take this exit IMMEDIATELY if at any point: ${scenario.description}`,
				parameters: ctx.EMPTY_PARAMS,
				execute: async (_args, { ctx: runCtx }) => {
					if (exited) return "already handled";
					exited = true;
					reportEvent(dispatch.callId, "flow.exit", {
						node: node.id,
						exit: scenario.name,
						target: scenario.target,
						scenario: true,
					});
					return followTarget(scenario.target, runCtx);
				},
			});
		}
		if (ctx.endCallEnabled) nodeTools.end_call = ctx.endCallTool;

		const exitNames = toolExits.map((e) => `exit_${sanitize(e.name)}`).join(", ");
		return voice.Agent.create({
			id: `node:${node.id}`,
			// Global job info is written ONCE on the agent and inherited by
			// every node; the node contributes only its stage instructions.
			// The transition rules below are what stop the two classic flow
			// failure modes: closing the conversation at every stage change,
			// and re-greeting/recapping after each handoff.
			instructions:
				ctx.globalInstructions +
				`\n\n## YOUR CURRENT STAGE\n${ctx.interpolate(node.instructions)}` +
				conversationReasonBlock +
				(hasObjectives
					? `\n\n## OBJECTIVES\nIn this stage you must learn the following from the caller, naturally and ONE question at a time:\n${objectives
							.map(
								(o) =>
									`- ${o.description}${
										o.options ? ` (record as one of: ${o.options.join(", ")})` : ""
									}${(o.required ?? true) ? "" : " (optional — don't push if they decline)"}`,
							)
							.join(
								"\n",
							)}\nThe system verifies these automatically as the caller answers and advances the conversation to the next stage on its own — never announce a stage change or rush the caller, and do not save these specific values with tools; they are recorded automatically.`
					: "") +
				summaryBlock +
				contactInfo +
				wrapUpBlock +
				(!isConversation && toolExits.length > 0
					? `\n\n## MOVING BETWEEN STAGES\nThis call flows through several stages and you handle ONLY this one. The moment the conversation satisfies an exit condition, call that exit tool (${exitNames}) IMMEDIATELY and SILENTLY. Changing stages is invisible to the caller: do NOT wrap up, do NOT say goodbye or "thanks for your time", do NOT announce a transfer or say you're passing them along — the very same voice simply continues the conversation.`
					: "") +
				(scenarios.length > 0
					? `\n\n## SCENARIOS\nThese scenario exits override your stage goal — call one the moment its condition appears: ${scenarios
							.map((s) => `exit_scenario_${sanitize(s.name)}`)
							.join(", ")}.`
					: "") +
				"\n\n## CONTINUITY\nThis is ONE continuous conversation. Never greet the caller again or re-introduce yourself after the call has started. Never repeat a question that was already answered — check the conversation before asking. Don't recap earlier answers unless you're confirming a correction. Vary your acknowledgements instead of repeating the same phrase." +
				"\n\n## IF SOMETHING FAILS\nIf a tool or action fails and you were not given specific wording to say, acknowledge it once briefly, do NOT repeat your last question, and offer to follow up (for example, note that someone will get back to them). Never pretend an action succeeded when it did not." +
				ctx.pacingRules +
				ctx.languageRules +
				(ctx.endCallEnabled
					? "\n\nOnly the end_call tool ends the call — moving between stages never ends it. Use end_call solely when the conversation is truly over and you've said goodbye."
					: "") +
				ctx.missingNote +
				ctx.prohibited,
			chatCtx,
			llm: node.llm ? ctx.buildLlm(node.llm) : ctx.defaultLlm,
			// A transfer node upstream switched the "person": this and every
			// later agent speaks with the post-transfer voice.
			tts: ctx.state.ttsOverride,
			tools: nodeTools,
			onEnter: (agentCtx) => {
				reportEvent(dispatch.callId, "flow.node", { node: node.id, name: node.name ?? null });
				// At most one conversation wrap-up timer is ever live: clear any timer
				// armed by a previous node before (re)arming below.
				if (ctx.state.conversationTimer) {
					clearTimeout(ctx.state.conversationTimer);
					ctx.state.conversationTimer = undefined;
				}
				// Arm (or disarm) the objective judge for this node. Rebuilt
				// fresh on every entry — re-entering a node restarts its goals.
				// Conversation nodes pass no objectives, so this always DISARMS the
				// judge for them (objective tracker never fires in conversation mode).
				getObjectivesTracker().arm({
					id: node.id,
					objectives,
					judge: node.judge,
					primaryExit: { name: objectivesPrimary?.name ?? "end", target: objectivesPrimary?.target },
				});
				// Conversation maxDurationSeconds (Phase 2): a SOFT cap. On expiry,
				// nudge the agent to wrap up via a generated turn (the least invasive
				// working mechanism — same generateReply path onEnter already uses;
				// no mid-node instruction rebuild). Never a hard cut: the model still
				// says a graceful line and then closes via end_call / the named exit.
				if (isConversation && conversation!.maxDurationSeconds) {
					ctx.state.conversationTimer = setTimeout(() => {
						ctx.state.conversationTimer = undefined;
						const sess = ctx.state.session;
						if (ctx.state.completed || !sess) return;
						if (sess.currentAgent.id !== `node:${node.id}`) return; // already moved on
						reportEvent(dispatch.callId, "flow.conversation_timeout", {
							node: node.id,
							seconds: conversation!.maxDurationSeconds,
						});
						sess.generateReply({
							instructions: `The time for this part of the call is up. Warmly bring the conversation to a close now in ONE brief sentence, then ${closeAction}.`,
						});
					}, conversation!.maxDurationSeconds * 1000);
				}
				// Entry node speech is the greeting (step 8) — except on a HANDOFF,
				// where the target's entry agent opens via the controller's nudge
				// (entryOnEnter fires here, inside the new activity's startup — the
				// only point where generateReply reliably lands on the NEW activity).
				// Later nodes open themselves. Not awaited — awaiting playout inside
				// a tool-triggered onEnter deadlocks the tool call.
				if (node.id === flow.entry) {
					entryOnEnter?.();
				} else {
					// If the last thing spoken is an agent question the caller
					// hasn't answered (an exit fired early, or speech queued
					// ahead of the handoff), opening this stage would stack a
					// second question on top of it — stay silent and let the
					// caller answer; the LLM resumes on their next turn.
					const lastSpoken = ctx.turns.filter((t) => t.role !== "system").at(-1);
					if (lastSpoken?.role === "agent" && lastSpoken.text.trim().endsWith("?")) {
						reportEvent(dispatch.callId, "flow.entry_silent", {
							node: node.id,
							pending_question: lastSpoken.text.slice(0, 200),
						});
						return;
					}
					agentCtx.session.generateReply({
						instructions:
							"Continue this same conversation mid-stream — no greeting, no re-introduction, no recap of what was already covered. " +
							(node.entryInstructions
								? ctx.interpolate(node.entryInstructions)
								: "Move naturally to this stage's first question."),
					});
				}
			},
		});
	};

	return { buildFlowAgent };
}
