import { llm, voice } from "@livekit/agents";
import { chatCtxMessages, reportAiTurn } from "../ai-log.js";
import { reportEvent } from "../gateway.js";
import { buildTools } from "../tools.js";
// Vendored copy of the canonical slug scheme (packages/shared/src/slugify.ts,
// also used by the gateway's agent-config schema). The worker builds standalone
// via `lk agent deploy`, so it can't import the workspace package —
// worker/src/vendor/ is regenerated by `pnpm sync:worker`. Exit-tool ids the LLM
// sees (`exit_${sanitize(name)}`) must equal the ids the gateway generated with
// the same transform, so both sides MUST derive from this one source.
import { slugify as sanitize } from "../vendor/slugify.js";
import { compactChatContext, type FlowRuntimeContext, tagRulesSatisfied } from "./context.js";
import type { ObjectivesTracker, ResolvedTarget } from "./objectives.js";

/**
 * Per-node agent assembly. A flow runs as a graph of small agents — one per
 * agent node, each with its own stage instructions and gated tools — connected
 * by exit tools that hand the session off to the next node (chat context
 * carried over, the previous node's prompt dropped).
 */

export interface AgentBuilder {
	buildFlowAgent(nodeId: string, chatCtx?: llm.ChatContext): voice.Agent;
	/** A `stop_responding` (park) node: a silent agent that never speaks or hangs
	 * up but keeps evaluating global scenarios each inbound turn so one can route
	 * the contact back out. Consumed by resolveTarget's `park` result. */
	buildParkedAgent(chatCtx?: llm.ChatContext): voice.Agent;
}

export interface AgentBuilderDeps {
	resolveTarget(target: string | undefined): Promise<ResolvedTarget>;
	/** simulated/cold: ends the LLM turn (throws StopResponse). warm: resolves
	 * with a result string once the attended transfer merges the parties. */
	runTransfer(nodeId: string): Promise<string>;
	/** Exit-tool entry into an agent-handoff (flow `handoff` node): start the
	 * detached fetch+swap sequence, then end the LLM turn with no reply. */
	runHandoff(target: {
		agentId: string;
		fromNode: string;
		transition?: { say?: string; holdSeconds?: number };
	}): never;
	/** The objectives tracker is constructed after this builder (it depends on
	 * buildFlowAgent), so it is reached lazily from onEnter. */
	getObjectivesTracker(): ObjectivesTracker;
	/** Fired from the ENTRY node's onEnter (once its activity is live). Set only
	 * when this build is a handoff target — flow/handoff's speak-first nudge.
	 * The call's own first agent passes none (the greeting opens the call). */
	entryOnEnter?: () => void;
	/** Detached transfer/handoff starters — used when a global scenario fires
	 * WHILE PARKED and routes onto a transfer/handoff target. The parked agent's
	 * turn hook is not a tool context, so it can't return an AgentHandoff; it drives
	 * these detached swaps directly (the same functions the objectives judge uses). */
	startTransfer(nodeId: string): void;
	startHandoff(target: { agentId: string; fromNode: string; transition?: { say?: string; holdSeconds?: number } }): void;
}

export function createAgentBuilder(ctx: FlowRuntimeContext, deps: AgentBuilderDeps): AgentBuilder {
	const { flow, nodesById, dispatch, bundle } = ctx;
	const { resolveTarget, runTransfer, runHandoff, getObjectivesTracker, entryOnEnter, startTransfer, startHandoff } =
		deps;

	/**
	 * Shared tail of every exit tool (regular exits and scenario exits):
	 * resolve the target through routers/statements, then hand off, hang up, or
	 * let an already-scheduled post-speech hangup run its course.
	 */
	const followTarget = async (
		target: string | undefined,
		runCtx: voice.RunContext,
	): Promise<string | llm.AgentHandoff> => {
		// An exit tool is executing — commit the transition NOW, before the (async)
		// resolveTarget + swap, so a same-turn end_call (parallel tool call) is
		// refused rather than killing the call mid-swap. Cleared once the next node
		// enters (onEnter below); for end/transfer/handoff resolutions the call is
		// either ending or covered by transferInFlight / handoff in-flight.
		ctx.state.transitionPending = true;
		ctx.state.lastTransitionAt = Date.now();
		// Routers/statements between here and the next agent node are evaluated
		// inline (routers: one LLM pass; statements: a queued say).
		const resolved = await resolveTarget(target);
		if (resolved.kind === "end") {
			// Abort-tolerant: caller may disconnect mid-playout (see end_call).
			await runCtx.waitForPlayout().catch(() => {});
			await ctx.hangUp("flow_complete");
			return "call ended";
		}
		if (resolved.kind === "end_after_speech") {
			// A terminal statement was queued and will hang up after playout —
			// do NOT hang up (or await playout) here: awaiting a queued speech
			// from inside a tool execution risks the drain deadlock.
			return "call ending";
		}
		if (resolved.kind === "transfer") {
			return runTransfer(resolved.nodeId);
		}
		if (resolved.kind === "handoff") {
			return runHandoff({
				agentId: resolved.agentId,
				fromNode: resolved.fromNode,
				transition: resolved.transition,
			});
		}
		if (resolved.kind === "park") {
			// Park the contact: swap in the silent parked agent. It never speaks or
			// hangs up (voice ends only via the existing silence timeout; text parks
			// indefinitely) but keeps evaluating global scenarios each inbound turn.
			const parkedCtx = runCtx.session.currentAgent.chatCtx.copy({ excludeInstructions: true });
			return llm.handoff({
				agent: buildParkedAgent(parkedCtx),
				returns: "Contact parked — the agent has stopped responding and is listening.",
			});
		}
		const nextCtx = runCtx.session.currentAgent.chatCtx.copy({
			excludeInstructions: true,
		});
		return llm.handoff({
			agent: buildFlowAgent(resolved.id, nextCtx),
			returns: `Moved to stage "${nodesById.get(resolved.id)?.name ?? resolved.id}".`,
		});
	};

	const buildFlowAgent = (nodeId: string, chatCtx?: llm.ChatContext): voice.Agent => {
		// Stamp every node→node swap: end_call refuses to fire near a transition,
		// so a model emitting end_call in the SAME turn as an exit tool (parallel
		// tool calls) can't kill the call mid-swap.
		ctx.state.lastTransitionAt = Date.now();
		const node = nodesById.get(nodeId);
		if (!node) throw new Error(`flow node "${nodeId}" not found`);
		if (
			node.kind === "router" ||
			node.kind === "statement" ||
			node.kind === "transfer" ||
			node.kind === "handoff" ||
			node.kind === "stop_responding"
		) {
			throw new Error(
				`flow node "${nodeId}" is a ${node.kind} — routers, statements, transfers, handoffs and stop_responding are evaluated inline via resolveTarget and never become plain flow agents`,
			);
		}

		// Rolling-memory compaction on node handoff (Phase 3): cap the carried-over
		// responder history to the last windowTurns verbatim turns; the condensed
		// older context rides in the `## CONVERSATION SO FAR` block below. Only the
		// responder-facing chatCtx is trimmed — `ctx.turns` (flush + judge) is untouched.
		if (chatCtx && ctx.memory.enabled) {
			const before = chatCtx.items.length;
			compactChatContext(chatCtx, ctx.memory.windowTurns);
			if (chatCtx.items.length < before) {
				reportEvent(dispatch.callId, "flow.memory_compact", {
					before,
					after: chatCtx.items.length,
					site: "handoff",
					node: node.id,
				});
			}
		}

		// Conversation mode (Phase 2): objective-less, self-driven open-ended
		// discovery. Mutually exclusive with objectives (schema-enforced).
		const conversation = node.conversation;
		const isConversation = !!conversation;
		const objectives = isConversation ? [] : (node.objectives ?? []);
		const hasObjectives = objectives.length > 0;

		// KNOWN CONTACT INFO (Phase 1 — the UNRESOLVED block). Rendered fresh on
		// every node entry from the shared mutable contactState, so a field written
		// in an earlier node shows its value here instead of UNRESOLVED. CRITICAL:
		// "UNRESOLVED" lives ONLY in this model-facing instruction string — it is
		// never a variable and never reaches interpolateSpoken/say, so it can never
		// be spoken. Empty list → no block at all.
		const contactInfo =
			ctx.contactState.length > 0
				? `\n\n## KNOWN CONTACT INFO\nYou already know these details about the caller. NEVER ask for a value shown here — if you need one, weave it in or confirm it naturally instead of asking. A field shown as UNRESOLVED is still unknown; those you MAY ask about. Never say the word "UNRESOLVED" aloud.\n${ctx.contactState
						.map((e) => `${e.label} -> ${e.value != null && e.value !== "" ? e.value : "UNRESOLVED"}`)
						.join("\n")}`
				: "";

		// Rolling summary (Phase 3): a condensed record of earlier turns, injected
		// into EVERY node kind between the global/stage instructions and the KNOWN
		// CONTACT INFO block. Empty until the first interval fires; a stale value is fine.
		const summaryText = ctx.rollingSummary.text.trim();
		const summaryBlock = summaryText
			? `\n\n## CONVERSATION SO FAR\nEarlier parts of this call, condensed (the most recent exchanges are still verbatim in the conversation below). Use this for continuity — never re-ask something already covered here:\n${summaryText}`
			: "";

		// Conversation-mode blocks (Phase 2). The reason (+ optional hints) replaces
		// the objectives block; closure is explicit rather than emergent.
		const conversationReasonBlock = isConversation
			? `\n\n## CONVERSATION REASON\n${ctx.interpolate(conversation!.reason)}${
					conversation!.hints?.length
						? `\n\nTalking points you can naturally explore (not a checklist — follow the caller's lead, one question at a time):\n${conversation!.hints
								.map((h) => `- ${ctx.interpolate(h)}`)
								.join("\n")}`
						: ""
				}`
			: "";
		const wrapUp = conversation?.wrapUp;
		const closeAction =
			wrapUp?.mode === "exit"
				? `call the exit_${sanitize(wrapUp.exit)} tool to move on`
				: "use the end_call tool to hang up";
		const wrapUpBlock = isConversation
			? `\n\n## WRAPPING UP\nYour DEFAULT is to KEEP THE CONVERSATION GOING: ask genuine, open-ended follow-up questions — ONE per reply — letting each answer lead naturally to the next angle. Do NOT wrap up just because a topic was covered; move to a fresh angle instead. Bring the call to a close ONLY when the CALLER clearly signals they are finished — they explicitly say they have nothing else or no more questions, they say goodbye, or they give repeated short, disengaged replies. When that clear signal comes, warmly acknowledge in ONE short line and then ${closeAction}. Never ask a question and end the call in the same reply: if you ask something, stop and wait for the answer.`
			: "";

		const nodeTools = buildTools(
			bundle.tools.filter((t) => node.toolIds.includes(t.id as string)),
			dispatch,
		);
		// Tag-driven exit gating (Phase 5b): an exit whose tagRules aren't
		// satisfied by the current tag set is NOT exposed here (and the objectives
		// primary falls through to the first non-gated exit). Evaluated at build
		// time — a mid-node tag change takes effect on the next handoff, when this
		// node (or the next) is rebuilt.
		const nonGatedExits = node.exits.filter((e) => tagRulesSatisfied(e.tagRules, ctx.contactTags));
		if (nonGatedExits.length < node.exits.length) {
			reportEvent(dispatch.callId, "flow.exits_gated", {
				node: node.id,
				gated: node.exits.filter((e) => !nonGatedExits.includes(e)).map((e) => e.name),
			});
		}
		// With objectives, the primary exit (the first NON-GATED exit) belongs to
		// the ENGINE — the judge takes it once the data is verified; the model gets
		// no tool for it (this is what stops eager exits). Secondary non-gated exits
		// ("Wrong number") stay model-callable. All exits gated → no primary: the
		// engine ends/continues per current no-exit semantics (warned below).
		const objectivesPrimary = hasObjectives ? nonGatedExits[0] : undefined;
		if (hasObjectives && node.exits.length > 0 && !objectivesPrimary) {
			reportEvent(dispatch.callId, "flow.no_available_exit", {
				node: node.id,
				reason: "all exits gated by tagRules",
			});
			console.warn(`flow: node "${node.id}" has objectives but every exit is tag-gated — objectives will end the call`);
		}
		const toolExits = hasObjectives ? nonGatedExits.slice(1) : nonGatedExits;
		// Guards against duplicate exit invocations from this node instance —
		// e.g. preemptiveGeneration drafting a reply (incl. tool calls) off an
		// interim transcript, then generating a second, final reply that calls
		// the same exit tool again once the caller's turn actually ends. Both
		// calls have real side effects (reportEvent + followTarget/handoff), so
		// the second one must be a no-op rather than replaying the transition.
		let exited = false;
		for (const exit of toolExits) {
			const target = exit.target;
			nodeTools[`exit_${sanitize(exit.name)}`] = llm.tool({
				description: `Take the "${exit.name}" exit: ${exit.description}${
					target ? "" : " This ends the call — say a brief goodbye first."
				}`,
				parameters: ctx.EMPTY_PARAMS,
				execute: async (_args, { ctx: runCtx }) => {
					if (exited) return "already handled";
					exited = true;
					reportEvent(dispatch.callId, "flow.exit", {
						node: node.id,
						exit: exit.name,
						target: target ?? null,
					});
					// Node-result variable (CloseBot "Nodes" Tier 1): an agent/conversation
					// node's outcome IS the exit it took. Objective nodes record their result
					// from the objectives tracker instead; a secondary exit taken here still
					// reflects the real outcome.
					ctx.recordNodeResult(node.id, { result: exit.name, succeeded: true });
					return followTarget(target, runCtx);
				},
			});
		}
		// Global scenarios (detect-and-jump): one extra exit per scenario on
		// every agent node, except a scenario already targeting this node.
		const scenarios = (flow.scenarios ?? []).filter((s) => s.target !== node.id);
		for (const scenario of scenarios) {
			nodeTools[`exit_scenario_${sanitize(scenario.name)}`] = llm.tool({
				description: `SCENARIO — take this exit IMMEDIATELY if at any point: ${scenario.description}`,
				parameters: ctx.EMPTY_PARAMS,
				execute: async (_args, { ctx: runCtx }) => {
					if (exited) return "already handled";
					exited = true;
					reportEvent(dispatch.callId, "flow.exit", {
						node: node.id,
						exit: scenario.name,
						target: scenario.target,
						scenario: true,
					});
					// Node-result variable (Tier 1): a scenario jump is this node's outcome.
					ctx.recordNodeResult(node.id, { result: scenario.name, succeeded: true });
					return followTarget(scenario.target, runCtx);
				},
			});
		}
		if (ctx.endCallEnabled) nodeTools.end_call = ctx.endCallTool;

		// Terminal node = the model may legitimately end_call here. Terminality is a
		// property of the node's FORWARD/PRIMARY path only — its primary exit (exits[0]).
		// A node is terminal when its primary exit ends the call (no target) or it has no
		// primary exit at all. EXCLUDED from the check: secondary exits (exits[1+], e.g.
		// "Wrong number" — model-callable side branches, not the forward path) and global
		// scenario exits (cross-cutting detect-and-jump, present on every node). The old
		// check looked at EVERY exit's target, so ANY node with a secondary targeted exit
		// was wrongly non-terminal and end_call could NEVER fire there (the live
		// never-ends regression). A conversation node whose wrapUp closes via end_call is
		// terminal by definition (it has no forward exit — it ends the call itself).
		const primaryForwardExit = node.exits[0];
		const wrapUpEndsCall = isConversation && conversation!.wrapUp.mode === "end_call";
		const isTerminalNode = wrapUpEndsCall || !primaryForwardExit || !primaryForwardExit.target;

		// Goodbye-loop backstop (installed on state below, for NON-terminal nodes only).
		// When the model repeatedly calls end_call on a non-terminal node — clearly
		// wanting to move on / thinking it's done — the shared end_call tool invokes
		// this after the refusal threshold to take THIS node's forward exit
		// programmatically, mirroring the objectives judge's transition switch. Any
		// still-pending objectives are simply abandoned (the next node re-arms the
		// judge), so the flow proceeds toward its terminal stage instead of hanging
		// open. The forward target is the engine's primary exit (the objectives primary
		// for objective nodes, else the first non-gated exit) — the same one the judge
		// or the model's forward exit would take.
		const autoAdvanceForwardExit = hasObjectives ? objectivesPrimary : nonGatedExits[0];
		const autoAdvanceTarget = autoAdvanceForwardExit?.target ?? primaryForwardExit?.target;
		const autoAdvanceForward = async (): Promise<void> => {
			const session = ctx.state.session;
			if (!session || ctx.isCompleted()) return;
			if (session.currentAgent.id !== `node:${node.id}`) return; // already moved on
			reportEvent(dispatch.callId, "flow.exit", {
				node: node.id,
				exit: autoAdvanceForwardExit?.name ?? "end",
				target: autoAdvanceTarget ?? null,
				via: "autoadvance",
			});
			// The node's outcome is a forced advance, not a satisfied exit.
			ctx.recordNodeResult(node.id, { result: "auto_advanced", succeeded: false });
			// Commit the transition before the async resolve/swap so a same-turn end_call
			// is refused rather than killing the call mid-advance (cleared on node entry).
			ctx.state.transitionPending = true;
			ctx.state.lastTransitionAt = Date.now();
			const resolved = await resolveTarget(autoAdvanceTarget);
			if (resolved.kind === "agent") {
				const nextCtx = session.currentAgent.chatCtx.copy({ excludeInstructions: true });
				session.updateAgent(buildFlowAgent(resolved.id, nextCtx));
			} else if (resolved.kind === "park") {
				const nextCtx = session.currentAgent.chatCtx.copy({ excludeInstructions: true });
				session.updateAgent(buildParkedAgent(nextCtx));
			} else if (resolved.kind === "end" || resolved.kind === "end_after_speech") {
				await ctx.hangUp("flow_complete");
			} else if (resolved.kind === "transfer") {
				startTransfer(resolved.nodeId);
			} else if (resolved.kind === "handoff") {
				startHandoff({ agentId: resolved.agentId, fromNode: resolved.fromNode, transition: resolved.transition });
			}
		};

		const exitNames = toolExits.map((e) => `exit_${sanitize(e.name)}`).join(", ");
		return voice.Agent.create({
			id: `node:${node.id}`,
			// Global job info is written ONCE on the agent and inherited by
			// every node; the node contributes only its stage instructions.
			// The transition rules below are what stop the two classic flow
			// failure modes: closing the conversation at every stage change,
			// and re-greeting/recapping after each handoff.
			instructions:
				ctx.globalInstructions +
				`\n\n## YOUR CURRENT STAGE\n${ctx.interpolate(node.instructions)}` +
				conversationReasonBlock +
				(hasObjectives
					? `\n\n## OBJECTIVES\nIn this stage you must learn the following from the caller. Draw each one out conversationally, ONE question at a time — acknowledge the caller's previous answer, then lead into the next in your own varied words. These are the FACTS to obtain, NOT scripts to read: never recite a field name or reuse the same question scaffold turn after turn.\n${objectives
							.map(
								(o) =>
									`- ${o.description}${
										o.options ? ` (record as one of: ${o.options.join(", ")})` : ""
									}${(o.required ?? true) ? "" : " (optional — don't push if they decline)"}`,
							)
							.join(
								"\n",
							)}\nThe system verifies these automatically as the caller answers and advances the conversation to the next stage on its own — never announce a stage change or rush the caller, and do not save these specific values with tools; they are recorded automatically.`
					: "") +
				summaryBlock +
				contactInfo +
				wrapUpBlock +
				(!isTerminalNode ? ctx.noEarlyWrapUp : "") +
				(!isConversation && toolExits.length > 0
					? `\n\n## MOVING BETWEEN STAGES\nThis call flows through several stages and you handle ONLY this one. The moment the conversation satisfies an exit condition, call that exit tool (${exitNames}) IMMEDIATELY and SILENTLY. Changing stages is invisible to the caller: do NOT wrap up, do NOT say goodbye or "thanks for your time", do NOT announce a transfer or say you're passing them along — the very same voice simply continues the conversation. When this stage's goal is met, move on to the next stage — never close the call or ask if there's "anything else" while any stage remains.`
					: "") +
				(scenarios.length > 0
					? `\n\n## SCENARIOS\nThese scenario exits override your stage goal — call one the moment its condition appears: ${scenarios
							.map((s) => `exit_scenario_${sanitize(s.name)}`)
							.join(", ")}.`
					: "") +
				"\n\n## CONTINUITY\nThis is ONE continuous conversation. Never greet the caller again or re-introduce yourself after the call has started. Never repeat a question that was already answered — check the conversation before asking. Don't recap earlier answers unless you're confirming a correction. Vary your acknowledgements instead of repeating the same phrase." +
				"\n\n## IF SOMETHING FAILS\nIf a tool or action fails and you were not given specific wording to say, acknowledge it once briefly, do NOT repeat your last question, and offer to follow up (for example, note that someone will get back to them). Never pretend an action succeeded when it did not." +
				ctx.pacingRules +
				ctx.conversationStyle +
				ctx.languageRules +
				ctx.textRules +
				ctx.responseStyle +
				(ctx.endCallEnabled
					? "\n\nOnly the end_call tool ends the call — moving between stages never ends it. Use end_call solely when the conversation is truly over and you've said goodbye."
					: "") +
				ctx.missingNote +
				ctx.prohibited,
			chatCtx,
			llm: node.llm ? ctx.buildLlm(node.llm) : ctx.defaultLlm,
			// A transfer node upstream switched the "person": this and every
			// later agent speaks with the post-transfer voice.
			tts: ctx.state.ttsOverride,
			tools: nodeTools,
			onEnter: (agentCtx) => {
				reportEvent(dispatch.callId, "flow.node", { node: node.id, name: node.name ?? null });
				// Baseline caller-turn count for this node's `attempts` result variable
				// (CloseBot "Nodes" Tier 1) — computed as the delta when the node completes.
				ctx.markNodeEntry(node.id);
				// This node is now live: the transition that led here is complete, so
				// clear the pending flag (the lastTransitionAt 5s window still covers the
				// immediate tail). And publish this node's terminality so the shared
				// end_call tool knows whether hanging up here is legitimate.
				ctx.state.transitionPending = false;
				ctx.state.currentNodeTerminal = isTerminalNode;
				// A fresh node's objectives are not yet complete — reset the
				// terminal-for-end_call override the previous node may have set.
				ctx.state.currentNodeObjectivesComplete = false;
				// Goodbye-loop backstop: expose THIS node's forward auto-advance to the
				// shared end_call tool (only for non-terminal nodes — a terminal node has
				// no forward exit, so end_call is legitimately allowed there and gets no
				// auto-advance). Entering a node is real progress, so reset the consecutive
				// refused-end_call counter — refusals only accumulate within one node.
				ctx.state.autoAdvance = isTerminalNode ? undefined : autoAdvanceForward;
				ctx.state.endCallRefusalNode = undefined;
				ctx.state.endCallRefusalCount = 0;
				// No-progress backstop governance: on an objective node the backstop only
				// resets on real flow progress (this entry, or an objective met/skipped),
				// so a looping agent is caught; on non-objective nodes every caller turn
				// resets it (session-lifecycle), so an open conversation is never cut.
				ctx.state.currentNodeHasObjectives = hasObjectives;
				// Entering a node IS flow progress — reset the no-progress timer.
				ctx.state.onProgress?.();
				// Leaving any prior parked state clears its explicit end timer.
				if (ctx.state.parkEndTimer) {
					clearTimeout(ctx.state.parkEndTimer);
					ctx.state.parkEndTimer = undefined;
				}
				// At most one conversation wrap-up timer is ever live: clear any timer
				// armed by a previous node before (re)arming below.
				if (ctx.state.conversationTimer) {
					clearTimeout(ctx.state.conversationTimer);
					ctx.state.conversationTimer = undefined;
				}
				// Arm (or disarm) the objective judge for this node. Rebuilt
				// fresh on every entry — re-entering a node restarts its goals.
				// Conversation nodes pass no objectives, so this always DISARMS the
				// judge for them (objective tracker never fires in conversation mode).
				getObjectivesTracker().arm({
					id: node.id,
					objectives,
					judge: node.judge,
					primaryExit: { name: objectivesPrimary?.name ?? "end", target: objectivesPrimary?.target },
				});
				// Conversation maxDurationSeconds (Phase 2): a SOFT cap. On expiry,
				// nudge the agent to wrap up via a generated turn (the least invasive
				// working mechanism — same generateReply path onEnter already uses;
				// no mid-node instruction rebuild). Never a hard cut: the model still
				// says a graceful line and then closes via end_call / the named exit.
				if (isConversation && conversation!.maxDurationSeconds) {
					ctx.state.conversationTimer = setTimeout(() => {
						ctx.state.conversationTimer = undefined;
						const sess = ctx.state.session;
						if (ctx.state.completed || !sess) return;
						if (sess.currentAgent.id !== `node:${node.id}`) return; // already moved on
						reportEvent(dispatch.callId, "flow.conversation_timeout", {
							node: node.id,
							seconds: conversation!.maxDurationSeconds,
						});
						sess.generateReply({
							instructions: `The time for this part of the call is up. Warmly bring the conversation to a close now in ONE brief sentence, then ${closeAction}.`,
						});
					}, conversation!.maxDurationSeconds * 1000);
				}
				// Entry node speech is the greeting (step 8) — except on a HANDOFF,
				// where the target's entry agent opens via the controller's nudge
				// (entryOnEnter fires here, inside the new activity's startup — the
				// only point where generateReply reliably lands on the NEW activity).
				// Later nodes open themselves. Not awaited — awaiting playout inside
				// a tool-triggered onEnter deadlocks the tool call.
				if (node.id === flow.entry) {
					entryOnEnter?.();
				} else {
					// If the last thing spoken is an agent question the caller
					// hasn't answered (an exit fired early, or speech queued
					// ahead of the handoff), opening this stage would stack a
					// second question on top of it — stay silent and let the
					// caller answer; the LLM resumes on their next turn.
					const lastSpoken = ctx.turns.filter((t) => t.role !== "system").at(-1);
					if (lastSpoken?.role === "agent" && lastSpoken.text.trim().endsWith("?")) {
						reportEvent(dispatch.callId, "flow.entry_silent", {
							node: node.id,
							pending_question: lastSpoken.text.slice(0, 200),
						});
						return;
					}
					agentCtx.session.generateReply({
						instructions:
							"Continue this same conversation mid-stream — no greeting, no re-introduction, no recap of what was already covered. " +
							(node.entryInstructions
								? ctx.interpolate(node.entryInstructions)
								: "Move naturally to this stage's first question."),
					});
				}
			},
		});
	};

	/**
	 * Evaluate the flow's global scenarios against the transcript so far, out of
	 * band (a dedicated LLM pass — the SAME pattern the router uses), and return
	 * the first matching scenario or null. Used only while parked: a parked agent
	 * never takes a normal reply turn (it throws StopResponse), so scenarios can't
	 * ride the model's reply-turn tool calls the way they do on a live node — they
	 * are evaluated here instead. Any error/miss resolves to "no scenario".
	 */
	const evaluateParkedScenarios = async (
		scenarios: { name: string; description: string; target?: string }[],
	): Promise<{ name: string; description: string; target?: string } | null> => {
		if (scenarios.length === 0) return null;
		const transcript = ctx.turns
			.filter((t) => t.role !== "system")
			.slice(-40)
			.map((t) => `${t.role === "user" ? "caller" : "agent"}: ${t.text}`)
			.join("\n");
		const evalCtx = new llm.ChatContext();
		evalCtx.addMessage({
			role: "system",
			content:
				"The agent has stopped responding and is only listening for specific scenarios. Given the conversation transcript, decide whether ANY listed scenario condition is now met. Answer with EXACTLY one scenario name from the list, or the single word none — the name only, nothing else.",
		});
		evalCtx.addMessage({
			role: "user",
			content: `Scenarios:\n${scenarios
				.map((s) => `- ${s.name}: ${s.description}`)
				.join("\n")}\n\nConversation transcript:\n${transcript}`,
		});
		// Same router-tier default as flow/router.ts: config.models.router wins,
		// else the Inference cheap default openai/gpt-4o-mini.
		const evalLlm = ctx.buildLlm({ model: ctx.models.router ?? "openai/gpt-4o-mini" });
		try {
			const res = await evalLlm.chat({ chatCtx: evalCtx }).collect();
			ctx.recordUsage("router", res.usage?.promptTokens ?? 0, res.usage?.completionTokens ?? 0);
			reportAiTurn(dispatch.callId, {
				class: "router",
				title: "Parked scenario check",
				model: evalLlm.model,
				promptTokens: res.usage?.promptTokens ?? 0,
				completionTokens: res.usage?.completionTokens ?? 0,
				request: chatCtxMessages(evalCtx),
				response: res.text,
			});
			const lower = res.text.trim().toLowerCase();
			if (!lower || lower === "none") return null;
			return (
				scenarios.find((s) => s.name.toLowerCase() === lower) ??
				scenarios.find((s) => lower.includes(s.name.toLowerCase())) ??
				null
			);
		} catch (err) {
			console.error("flow: parked scenario evaluation failed", err);
			return null;
		}
	};

	/** Drive a resolved scenario target out of the parked state (detached — not a
	 * tool context). Mirrors the objectives judge's transition switch. */
	const routeOutOfPark = (resolved: ResolvedTarget, session: voice.AgentSession): void => {
		// Leaving park: cancel the explicit voice park-end timer.
		if (ctx.state.parkEndTimer) {
			clearTimeout(ctx.state.parkEndTimer);
			ctx.state.parkEndTimer = undefined;
		}
		if (resolved.kind === "agent") {
			const nextCtx = session.currentAgent.chatCtx.copy({ excludeInstructions: true });
			session.updateAgent(buildFlowAgent(resolved.id, nextCtx));
		} else if (resolved.kind === "end") {
			void ctx.hangUp("flow_complete");
		} else if (resolved.kind === "transfer") {
			startTransfer(resolved.nodeId);
		} else if (resolved.kind === "handoff") {
			startHandoff({ agentId: resolved.agentId, fromNode: resolved.fromNode, transition: resolved.transition });
		} else if (resolved.kind === "park") {
			// Scenario routed onto ANOTHER stop_responding node — re-park.
			const nextCtx = session.currentAgent.chatCtx.copy({ excludeInstructions: true });
			session.updateAgent(buildParkedAgent(nextCtx));
		}
		// end_after_speech: a terminal statement queued its own hangup — nothing here.
	};

	/**
	 * Parked agent (a `stop_responding` node). The agent has stopped responding to
	 * the contact but the session stays alive and listening:
	 *  - onEnter marks the runtime parked and disarms the prior node's judge/timer.
	 *    It NEVER generates a reply, so entering park is silent.
	 *  - The turn hook throws StopResponse on every inbound turn, so the agent never
	 *    speaks — no proactive message, no reply. Before doing so it evaluates the
	 *    global scenarios out of band; if one fires, the contact is routed out of
	 *    park onto that scenario's branch.
	 *  - It carries NO forward exits and NO end_call tool, and publishes
	 *    currentNodeTerminal=false so the shared end_call tool refuses here: park
	 *    parks, it never hangs up. Voice calls still end via the existing silence
	 *    timeout; text sessions park indefinitely.
	 */
	const buildParkedAgent = (chatCtx?: llm.ChatContext): voice.Agent => {
		ctx.state.lastTransitionAt = Date.now();
		const scenarios = flow.scenarios ?? [];
		const agent = voice.Agent.create({
			id: "park",
			instructions:
				ctx.globalInstructions +
				"\n\n## LISTENING MODE\nYou have stopped responding to the contact. Do NOT send any message, reply, greeting, or acknowledgement of any kind — produce no output at all. Remain silent and keep listening.",
			chatCtx,
			llm: ctx.defaultLlm,
			// Post-transfer voice (if any) carries over; parked never speaks anyway.
			tts: ctx.state.ttsOverride,
			tools: {},
			onEnter: () => {
				reportEvent(dispatch.callId, "flow.parked", { scenarios: scenarios.length });
				ctx.state.parked = true;
				// NOT a terminal node: end_call must refuse here — park never hangs up.
				ctx.state.currentNodeTerminal = false;
				ctx.state.currentNodeObjectivesComplete = false;
				ctx.state.transitionPending = false;
				// Park has no forward exit and no end_call tool: never auto-advance from
				// here, and drop any prior node's counter/hook.
				ctx.state.autoAdvance = undefined;
				ctx.state.endCallRefusalNode = undefined;
				ctx.state.endCallRefusalCount = 0;
				// Not an objective node: caller turns reset the no-progress backstop so a
				// parked contact isn't force-ended by it (park end is governed below / by
				// maxCall). Entering park is itself progress.
				ctx.state.currentNodeHasObjectives = false;
				ctx.state.onProgress?.();
				// Disarm the previous node's objective judge and any conversation timer.
				getObjectivesTracker().arm({ id: "park", objectives: [], primaryExit: { name: "end" } });
				if (ctx.state.conversationTimer) {
					clearTimeout(ctx.state.conversationTimer);
					ctx.state.conversationTimer = undefined;
				}
				// VOICE park-end backstop: the parked agent never speaks, so the ordinary
				// silence timeout (reset on every committed turn) can be held open forever
				// by a caller who keeps talking to a silent line. Arm an EXPLICIT end timer
				// that is NOT reset by turns so a parked voice call reliably closes. Text
				// parks indefinitely by design (governed by inactivity + maxCall).
				if (ctx.state.parkEndTimer) clearTimeout(ctx.state.parkEndTimer);
				ctx.state.parkEndTimer = undefined;
				if (ctx.dispatch.channel !== "text") {
					// Read-site default: legacy configs may omit the field (NaN → instant hangup).
					const parkEndSeconds = ctx.config.timeouts.silenceHangupSeconds ?? 30;
					const parkEndMs = parkEndSeconds * 1000;
					ctx.state.parkEndTimer = setTimeout(() => {
						ctx.state.parkEndTimer = undefined;
						if (ctx.state.completed) return;
						if (ctx.state.session?.currentAgent.id !== "park") return; // routed out
						reportEvent(dispatch.callId, "flow.park_timeout", { seconds: parkEndSeconds });
						void ctx.hangUp("park_timeout");
					}, parkEndMs);
				}
			},
		});
		// Suppress every reply turn while parked. StopResponse (honored by the SDK in
		// onUserTurnCompleted) skips the model's reply generation entirely, so the
		// agent stays silent — but we first run scenario evaluation so an inbound
		// message can still pull the contact out of park.
		agent.onUserTurnCompleted = async () => {
			if (!ctx.state.parked || ctx.state.completed) throw new voice.StopResponse();
			const matched = await evaluateParkedScenarios(scenarios);
			if (matched && ctx.state.parked && !ctx.state.completed) {
				ctx.state.parked = false;
				reportEvent(dispatch.callId, "flow.exit", {
					node: "park",
					exit: matched.name,
					target: matched.target ?? null,
					scenario: true,
				});
				const resolved = await resolveTarget(matched.target);
				const session = ctx.state.session;
				if (session) routeOutOfPark(resolved, session);
			}
			throw new voice.StopResponse();
		};
		return agent;
	};

	return { buildFlowAgent, buildParkedAgent };
}
